### ISSUE TITLE
Command Recipe Suggestion

### ISSUE THREAD

**Issue by ArcticRaven** [2008Choco/Alchema#11]
**Describe the new feature**
An option to execute a command on brew completion

**How will it work?**
This would be a config option just to execute a command on recipe completion. This would allow just about any plugin to be used as a Product in the brews provided that the right player can be targeted on brew completion. 

**Does this require integration with another plugin?**
Nope :D

**Comment by 2008Choco** [comment]
This has technically been resolved by [72c77bc](https://github.com/2008Choco/Alchema/commit/72c77bce55d2c7e21a69e2e1cc841522966c5096) and will be available in a future version. `alchema:item` ingredients and result items will now support NBT
```json
{
    "result": {
        "item": "minecraft:diamond_sword{Enchantments:[{id:\"minecraft:sharpness\",lvl:5}],display:{Name:\"Hello world!\"}}"
    },
    "ingredients": [
        {
            "type": "alchema:material",
            "item": "minecraft:diamond",
            "amount": 2
        },
        {
            "type": "alchema:material",
            "item": "minecraft:stick"
        }
    ]
}
```
