### ISSUE TITLE
Right clicking on cauldron with item.

### ISSUE THREAD

**Issue by Deadpan110** [2008Choco/Alchema#3]
Version 1.0.1.0

It would seem that right clicking the cauldron with an ingredient causes the item to be destroyed by the heat source.

Can I suggest that either this accidental right click with an item will block the unintended action or allow the cauldron to accept the ingredients in this way?

Fun plugin BTW!

**Comment by 2008Choco** [comment]
I cannot replicate this with some of the default recipes. Could you give more information about how you're replicating this? With what item are you right clicking the cauldron? Do you have a video of this that can help me better identify the bug? A list of the plugins you are running might also be of use 🙂 

I don't do any right click handling in the plugin at all so I'm unsure as to what may be causing this. It may even be another plugin. (Thank you, by the way! Happy you're enjoying it!)

**Comment by Deadpan110** [comment]
I right clicked with 2 diamonds and both burned.
I have not had time today, however - based on your info, it may have something to do with this plugin:
https://www.spigotmc.org/resources/brewery.3082/
It is possibly (very likely) an incompatibility issue and nothing to do with your plugin at all.
(we have only just started the server and have added things of interest - no one has yet made brews in brewery - but for the time being, I am running both side-by-side).
Also, when time permits; I can gladly provide more info.
I would consider this as an incompatibility and not a bug (more testing soon TM).
Keep up the great work.

**Comment by 2008Choco** [comment]
Yes, after looking at the source code of brewery, it has a similar feature in that it has heated cauldrons with fire and accepts ingredients by right clicking items onto the cauldron. So this is most definitely not an issue with Alchema, it's just a feature of Brewery 😄

Brewery, as far as I can tell, uses boiling cauldrons and right clicking ingredients into it to brew items such as fermented wheat, boiled herbs, etc. You can see their available recipes under their config.yml, `cauldron.ex`
