### ISSUE TITLE
Recipes for cobblestone -> gravel, gravel -> sand

### ISSUE THREAD

**Issue by Deadpan110** [2008Choco/Alchema#5]
I added this to our server as some people like to build and not have to grind all that much.

I figured I would share the json here for others to see/use (or perhaps you can use it in examples).

Cobblestone -> Gravel -> Sand while using Flint as the grinding/alchema ingredient to make it work:

**Cobblestone into Gravel:**

```
{
    "result": {
        "item": "minecraft:gravel",
        "amount": 8
    },
    "ingredients": [
        {
            "type": "alchema:material",
            "item": "minecraft:cobblestone",
			"amount": 8
        },
        {
            "type": "alchema:material",
            "item": "minecraft:flint"
        }
    ]
}
```
**Gravel into Sand:**

```
{
    "result": {
        "item": "minecraft:sand",
        "amount": 8
    },
    "ingredients": [
        {
            "type": "alchema:material",
            "item": "minecraft:gravel",
			"amount": 8
        },
        {
            "type": "alchema:material",
            "item": "minecraft:flint"
        }
    ]
}
```

**Comment by 2008Choco** [comment]
This reminds me a lot of Ex Nihilo's hammers from mod packs like Skyfactory 🙂 I would be all for including these as default recipes if you grant me permission to do so. Much like I did with [the default concrete recipes](https://github.com/2008Choco/Alchema/commit/44361c165350936c5b53be2303d5b590a11b5b19) that were suggested to me, I may leave a comment in the JSON file attributing the resources to your user (or some other name if you so choose - do let me know)

**Comment by Deadpan110** [comment]
Please feel free to use the recipes, I am glad to contribute to your great/fun plugin!

:)

**Comment by 2008Choco** [comment]
Closing for now. Will be available in the next release! I've left a comment in the JSON files to attribute the recipes to you. Thank you!
