### ISSUE TITLE
Allow Custom Names and Model Data for brewed items

### ISSUE THREAD

**Issue by ArcticRaven** [2008Choco/Alchema#8]
**Describe the new feature**
Add ability to add custom item names and attach model data to the output items

**How will it work?**
add a "Name" and "CustomModelData" option to the Json files for the items

**Does this require integration with another plugin?**
I would really hope not :p

**Comment by 2008Choco** [comment]
This is already possible :) The `result` can accept pretty much any NBT though the format is undocumented. I should really write an example item in a JSON file for reference. As for your two requests:
```json
{
    ...
    "result": {
        "item": "minecraft:diamond_sword",
        "name": "&cCustom Sword",
        "custom_model_data": 10
    }
    ...
}
```

**Comment by ArcticRaven** [comment]
sweet :dab:
